### ISSUE TITLE
This is AWESOME but,

### ISSUE THREAD

**Issue by davidpolyakov** [iso-athletic/iso-app#33]
1. spelled Dererk Pardon's name wrong (not sure if that matters but just a thought), 2. Put the players' names in alphabetical order so it's easier to input especially when teams/drills change quickly, 3. put in more than 5 names per team so teams can be larger than five. 4. make an option to add more than two teams. sometimes drills are 3 v. 3 v. 3. etc. Lastly, and most important, highlight the cell that was just clicked on with a color or a box to make it easier to recognize a mistake or know what button you are hitting.

The app looks incredible though!

**Comment by joecummings** [comment]
Just split up these into individual comments so it'll be easier for us to tackle. Thanks so much for your feedback!
